name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
          pip install poetry
          make install
          pip install pyyaml
          
    - name: Install pytest
      run: pip install pytest
    - name: Run tests
      run: pytest
    
      
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.2.0
      if: github.ref_name == 'main'
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: make test-coverage
        debug: true
